---
# Force CLI for eos_command to ensure running config is returned properly
- name: Gather EOS configuration
  eos_command:
    commands='show running-config all'
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport='cli'
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  register: output

- set_fact:
    base_config='{{ output.result[0] }}'

- name: Arista EOS VLAN resources
  eos_template:
    src=vlan.j2
    include_defaults=True
    config={{ base_config|default(omit) }}
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport={{ transport|default(omit) }}
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  when: vlans is defined
  with_items: '{{ vlans }}'

- name: Arista EOS switchport resources
  eos_template:
    src=switchport.j2
    include_defaults=True
    config={{ base_config|default(omit) }}
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport={{ transport|default(omit) }}
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  when: switchports is defined
  with_items: '{{ switchports }}'
