# Perform the EOS interface tasks under Ansible 2.1 or earlier
# using the Ansible eos_template module
- name: Arista EOS VLAN resources (Ansible <= 2.1)
  eos_template:
    src: vlan.j2
    include_defaults: True
    config: "{{ _eos_config | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when: vlans is defined
  with_items: "{{ vlans | default([]) }}"

- name: Arista EOS purge VLAN resources (Ansible <= 2.1)
  eos_template:
    src: purge_vlans.j2
    include_defaults: True
    config: "{{ _eos_config | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when:
    eos_purge_vlans is defined and
    eos_purge_vlans and
    vlans is defined
  with_items: "{{ eos_purge_vlans | default([]) }}"

- name: Arista EOS switchport resources (Ansible <= 2.1)
  eos_template:
    src: switchport.j2
    include_defaults: True
    config: "{{ _eos_config | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when: switchports is defined
  with_items: "{{ switchports | default([]) }}"
